# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/database-config',
                'doc_host': 'https://schlinkertc.github.io',
                'git_url': 'https://github.com/schlinkertc/database-config',
                'lib_path': 'database_config'},
  'syms': {'database_config.core': {'database_config.core.foo': ('core.html#foo', 'database_config/core.py')}}}
